### ISSUE TITLE
Не обновляется "Плейлист дня" и др.

### ISSUE THREAD

**Issue by progman27** [Angel777d/kodi.plugin.yandex-music#1]
Спасибо за плагин, работает отлично. Но заметил проблему-не обновляется плейлист дня и другие плейлисты, пока не обновишь их в приложении ям.

**Comment by Angel777d** [comment]
Да, есть такое.
Чинится не очевидно и тестировать сложно. Поправлю на выходных наверно.

**Comment by progman27** [comment]
Было бы здорово, спасибо! Если надо, могу помочь потестировать и логи предоставить.

**Comment by progman27** [comment]
Ещё заметил, что иногда коди вылетает при переключении на следующий трек или при переходе на другой трек плейлиста. Коди версии 18.6

**Comment by Angel777d** [comment]
Может быть конечно. 
В случае если падает питон - можно найти в логах ошибку.
Буду признателен, если удастся найти и прислать.

**Comment by progman27** [comment]
Конечно, попробую поймать в логе этот момент, включил в коди запись всех логов, жду) Может проблема в нехватке памяти и андроид выгружает коди, ведь он много требует для работы ресурсов, у меня он установлен на тв боксе zidoo x9s, в нём 2 gb оперативки.

P. S. Прямо магия, ни разу за целый день не упал коди, специально переходил по плейлисту часто, всё ок. Может это потому, что ничего не запускал на боксе сегодня, и памяти хватало, тогда дело и не в плагине вовсе...

**Comment by Angel777d** [comment]
Залил свежий билд с фиксом
