### ISSUE TITLE
не может залогинится

### ISSUE THREAD

**Issue by vtolstov** [Angel777d/kodi.plugin.yandex-music#11]
ввожу точно верный логин и пароль, но говорит что не может авторизоваться
версия плагина 0.1.5

**Comment by vtolstov** [comment]
зато с версией 0.1.2 норм залогинилось

**Comment by Angel777d** [comment]
В версии  1.3 обновилась библиотека яндекс-музыки - завезли новую авторизацию.
В текущей версии авторизаию из библиотеки вырезали совсем (еще не добавлял в плагин)
Это связанго с тем, что на разных аккаунтах авторизация по логину-паролю проходит по разному и не всегда работает корректно.

Можно из настроек плагина в версии 1.2 взять токен и сохранить себе куда-нибудь.
После чего спокойно обновиться до последней версии и проверить что токен указан верно в настройках плагина.

**Comment by vtolstov** [comment]
понял, спасибо

**Comment by dE1l** [comment]
Правильно ли я понимаю, что речь идет про копирование настроек, которые на РасберианОС хранятся тут:
/home/pi/.kodi/userdata/addon_data/plugin.yandex-music/settings.xml
В этом файле должен появиться токен ?

**Comment by Angel777d** [comment]
> 

Да, похоже на правду.
кроме того можно прям в настройках плагина найти в приложении.
