### ISSUE TITLE
Can't login to my yandex account

### ISSUE THREAD

**Issue by n4meless0ne** [Angel777d/kodi.plugin.yandex-music#12]
Hi, just installed Kodi and this plugin. 
I have Redmi Note 8, Android 11,  Kody 19.3, plugin version 0.1.5. 

Can't login with error: 

Login Error:
Can't login with: my_login | my_password

I can provide additional information if you need it. I don't have paid yandex music subscription, my be that's the answer?

**Comment by Angel777d** [comment]
Hi!
There is an issue with login to Yandex account on Yandex side.
You can try to switch your Yandex account to 2FA auth mode and maybe it will help.

Other way is to get auth token directly: https://github.com/MarshalX/yandex-music-api/discussions/513#discussioncomment-2729781
You can add token to plugin settings and it will be used instead regular login.

**Comment by n4meless0ne** [comment]
Hi!
Thanks for your help - it's working!

**Comment by Angel777d** [comment]
You are welcome!

**Comment by progman27** [comment]
Wrong login account again on Kodi 19.4 and plugin 0.1.5
Login Error:
Can't login with: my_login | my_password

**Comment by KirMozor** [comment]
> Wrong login account again on Kodi 19.4 and plugin 0.1.5 Login Error: Can't login with: my_login | my_password

Same thing

**Comment by progman27** [comment]
> > Wrong login account again on Kodi 19.4 and plugin 0.1.5 Login Error: Can't login with: my_login | my_password
> 
> Same thing

If you install KODI version 18.9 and plugin 0.0.39 everything works. Then you can update KODI and the plugin and it will work. But it's a crutch)

**Comment by Angel777d** [comment]
Yeah, there is an issue with login in yandex music api. 
One solution is to try 2FA and use password from yandex.key application.
Other one described here: https://github.com/MarshalX/yandex-music-api/discussions/513#discussioncomment-2729781
(get an api key and put in in settings mannualy)

**Comment by progman27** [comment]
> Yeah, there is an issue with login in yandex music api. One solution is to try 2FA and use password from yandex.key application. Other one described here: [MarshalX/yandex-music-api#513 (comment)](https://github.com/MarshalX/yandex-music-api/discussions/513#discussioncomment-2729781) (get an api key and put in in settings mannualy)

on older plugin 0.0.39 all work, maybe adaptive this plugin for kodi 19.x ?

**Comment by Angel777d** [comment]
Older plugin works with older version of yandex music api and have own login issues.
It will work for you but will not for other users.
