### ISSUE TITLE
Добавить инструкцию о том, как получить токен

### ISSUE THREAD

**Issue by asm0dey** [Angel777d/kodi.plugin.yandex-music#4]
Спасибо за аддон!

К сожалению, для аутентификации нужно использовать пользователя и токен, но абсолютно непонятно, где этот токен брать, а без него музыка играет только по 30 секунд.

**Comment by Angel777d** [comment]
А при первом запуске разве нет опции логина?

**Comment by Angel777d** [comment]
Но инструкция не помешает. Добавлю.

**Comment by asm0dey** [comment]
Есть! Я, как обычно, сначала полез в настройки, а открыть даже не попробовал. Спасибо :)

**Comment by Angel777d** [comment]
Что то у меня плохо с написанием инструкций.
Добавил пару слов в Readme.
