### ISSUE TITLE
Добавить плейлисты.

### ISSUE THREAD

**Issue by lenych** [Angel777d/kodi.plugin.yandex-music#5]
Добрый день.
Есть ли возможность добавить в плагин плейлист "Чарт" https://music.yandex.ru/chart
и сделать навигацию по подборкам плейлистов https://music.yandex.ru/genres

**Comment by Angel777d** [comment]
Думаю можно.
 Будет время доберусь сделаю.

**Comment by Angel777d** [comment]
Добавил чарт. 
Как вытащить подборки по жанрам не очень понятно - их нет в виндовом клиенте, только в вебе.
Но можно использовать радио - там жанры есть.
