### ISSUE TITLE
Не проходит авторизация

### ISSUE THREAD

**Issue by Funk2256** [Angel777d/kodi.plugin.yandex-music#8]
Доюрого всем, при установке плагина на arm7 не удается пройти авторизацию. Как быть? Лог/пасс верные

**Comment by Angel777d** [comment]
Яндекс выкатил новую авторизацию. В библиотеке вроде уже есть фикс. Сделаю - надо будет проверить. Не на всех аккаунтах ещё работает.

**Comment by Angel777d** [comment]
Залил версию  0.1.3 с новой библиотекой.
Должно работать.

**Comment by Angel777d** [comment]
> Доюрого всем, при установке плагина на arm7 не удается пройти авторизацию. Как быть? Лог/пасс верные

Очень большая просьба проверить и отписаться сюда. А то я переживаю )

**Comment by Funk2256** [comment]
Добрый день, опять решил поднять коди, и опять столкнулся с проблемой
авторизации в вашем приложении, там требуется логин и токен, не подскажете
где взять данный токен? т.к. пройти авторизацию не удается а на гитхабе не
совсем понятно в инструкции описано прохождение авторизации

сб, 24 апр. 2021 г. в 17:34, Dmitry ***@***.***>:

**Comment by Angel777d** [comment]
Логиниться нужно в плагине через логин и пароль.
Запустить плагин.
Выбрать строку Login
Ввести логин.
Ввесли пароль.
В настройках ничего делать не нужно, на токен не надо обращать внимание.

**Comment by Funk2256** [comment]
Я вас понял, только вот поля ввода пароля отсутствует.

вт, 5 окт. 2021 г., 00:26 Dmitry ***@***.***>:

**Comment by Angel777d** [comment]
Добавил инструкцию в картинках [как логинться](https://github.com/Angel777d/kodi.plugin.yandex-music/blob/master/LOGIN.md)

А вот что было написано в ридми
> Настройка:
Все возможности плагина станут доступны после логина в аккаунт Яндекса.
Запустите плагин и передите в поле Login.
Введите ваш логин и пароль.
Плагин не хранит пароль. Яндекс сгенерит токен. Токен можно найти в настройках плагина.

заменил на:
>Все возможности плагина станут доступны после логина в аккаунт Яндекса.
Запустите плагин и передите в поле Login.
Введите ваш логин и нажмите OK.
Введите ваш пароль и нажмите OK.
Плагин не хранит пароль. Яндекс сгенерит токен. Токен можно найти в настройках плагина.
